-- MySQL Script generated by MySQL Workbench
-- 06/23/15 20:24:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_jordana
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_jordana
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_jordana` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `bd_jordana` ;

-- -----------------------------------------------------
-- Table `bd_jordana`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jordana`.`Cliente` (
  `idCliente` INT NOT NULL,
  `emailCliente` VARCHAR(45) NOT NULL,
  `nombresCliente` VARCHAR(60) NOT NULL,
  `apellidosCliente` VARCHAR(60) NOT NULL,
  `direccionCliente` VARCHAR(45) NOT NULL,
  `telefonoCliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `emailCliente_UNIQUE` (`emailCliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_jordana`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jordana`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(60) NOT NULL,
  `descripcionProducto` VARCHAR(45) NOT NULL,
  `precioProducto` DECIMAL(8,2) NOT NULL,
  `idCategoria` INT NOT NULL,
  `stockProducto` INT NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_jordana`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jordana`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_jordana`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jordana`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `emailUsuario` VARCHAR(60) NULL,
  `passwordUsuario` VARCHAR(50) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `emailUsuario_UNIQUE` (`emailUsuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_jordana`.`Producto_en_Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jordana`.`Producto_en_Categoria` (
  `idProducto` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `idCategoria`),
  INDEX `fk_Producto_has_Categoria_Categoria1_idx` (`idCategoria` ASC),
  INDEX `fk_Producto_has_Categoria_Producto_idx` (`idProducto` ASC),
  CONSTRAINT `fk_Producto_has_Categoria_Producto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `bd_jordana`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Categoria_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `bd_jordana`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


/*Categorias*/
INSERT INTO categoria (nombreCategoria) VALUES ('Frutas');
INSERT INTO categoria (nombreCategoria) VALUES ('Verduras');
/*
INSERT INTO categoria (nombreCategoria) VALUES ('Setas');
INSERT INTO categoria (nombreCategoria) VALUES ('Hierbas');
INSERT INTO categoria (nombreCategoria) VALUES ('Delicatessen');
INSERT INTO categoria (nombreCategoria) VALUES ('Ofertas');
INSERT INTO categoria (nombreCategoria) VALUES ('ProductosTemporada');
INSERT INTO categoria (nombreCategoria) VALUES ('ProximaCosecha');
*/

